### ISSUE TITLE
task list

### ISSUE THREAD

**Issue by tmarinatucker** [tmarinatucker/markdown-portfolio#2]
- [x] Additional markup is supported, including @mentions, #references, [links](url), **emphasis**, and <del>HTML tags</del>.
- [x] List syntax is required.
  - You can nest lists below, too!
- [x] This item is completed.
- [x] This item is not complete.

**Comment by tmarinatucker** [comment]
- [x] Additional markup is supported, including @mentions, #references, [links](url), **emphasis**, and <del>HTML tags</del>.
- [x] List syntax is required.
  - You can nest lists below, too!
- [x] This item is completed.
- [ ] This item is not complete.
